travis:
  secure:
    BINSTAR_TOKEN: 5Ijy86x42wKiBWXT2H0A6N2CV74zEfRxz6nvO08im8V2FagzMP0i9LVr76s7M392ZyMYRkIMI5R7xzzI7aIV/TH34SyaQlYGeGkql38nJTaayt2whwcRbkNRKh0NeEgUaYqhDZDjZyAsDoS/CAUMBrafUmGRib4WkYOzJ2Q2BUw46zXSgBRgSXdeUUZRqBS/PQ4NotbHfxF0zXUKO01qUKjQ3O0TSwqtbAwSrG6MAFAvWajnLaWBa9WpE5bD0NKTO/LTg+05CQ65hZVTz1nj33VYg5pyMzXTQW6rmcnLqVloBchUwu3z3rgBWyFLJ5hd/kpT0aU1CC4qCTrE6TUytSDoQqAYce1etxV+cbM7+9w/JsfgX6jMcxhkpufarY82VPTEQCd9JqjP665f+giDMkfTGIhk8rKZPHtydVDxvXxqRMdtBi2HQ4mTtrCClBPmLVnA9vDM8C42lH3r6KWcpcKBFqkzZRB89ewRMQPEOTox/z269/1seLsoDpftDu+OkzENw7X6djNKmqyVvPzmc9KbygRyROByLB7dsd9NyvBBR1J5O4R6LN2qRsk+N1PFToe5LiBpI4mNbAqaLlzJ5WySeO2yQPOtKGzfVMBxn7C3TkBhkSpBahdl3DCvwte8j8ytJjKkzi0+K9p76i2JlgzEOWgnB6OGtk1mAvUJiaw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
