travis:
  secure:
    BINSTAR_TOKEN: Ex6hjNCoVAGXaLoJcT1U9IUtE7AdTSMJEZvj8M2C3xuHS2jzdQgX2S6p9WFF8UmqZHIPCo6gIECDPE7WdE+VWii0mRJvVTIEifl4b1CLNiLC6XNCUN0mZyjrktdhITbWA/LRd9rYruMyBFrI5+8/ka4dQ0TkTZw1KTuTyiMZMXNX9IEOT18TQtFL8KwgHVzRH03IrXDGTj2jpM/FYCTtQ79WVsXK9PXXgLTlgnLUn3ELBX74t7qnS8ChgHNvmHFey6ZT/pYtUAKItMjFYfAYqtY6BwVIPRwtHQl56uYs9u745w6Jp9nxn5ND9yfjzWuh8lI6Nz/ExCYuN2JJmuDlEmJl+NmbkoxBL+HZXwHN3XDbc5OkVcDfYYiYm9As5ZpFq/giAyDHF7McgHvQrYO0FUX78P4+8Eet4se75Vy8JHHEiKpXF+bpzeqoBOXlFbVUF+qRdPxBEnmimoImvuFnChFpmRmoTfoIXEHWYNFOPjPB7sFSSv+IBmLnGiYeGsQt76RhFBDPEryHyWaR/Af2r166AZ+f1y2eg/+jglCrCrNY3tUhHqZuuGwjZi1pgkxtsXHrlmQcKUJv31DXfB/Vxly3XjhzhW/E6qI4WvB2mPpB9fdbBeGwLAnHX/EOYrLEiZ/Bz8+j8qGMI++x1lrclFYBt+txN/qv75Rsy4+T+7E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
