travis:
  secure:
    BINSTAR_TOKEN: lG0i2eR0h0LGGePIwAmsDmwslvD5V+RIZm0yo45ttMZrC2hLHWH6mUJU96Kg3ZfV+u6DPohaVQ1QPIJs4+EsPB7zExJ+r/S0/4etKO6Aq86Ig6jL/GsWD31FhXC420xrLMs06iB+MWDUNmyQcLpOJz3ITEj0pkIM9egB2HhjNOqCz57nNeOZnh18qu9wk+cS79lLoWF5pQ8iK7EwVYuU82XmFFszTFBvHfm/pI/jwqhuozME/eNu8vkhuUZpOSB7yjTYPTiBo6ySDL2lxi9TbduBW6H3Pl9PGOFDdIxFn3HeXaUJEnyHEqg140KIGmKItJXG7xW7M/a4VNkhFoTuvzMBGr6C5D//fiiX8JgQOXMS1PdX9GXdsMapiIIWpXdRj0G6UThH6xS/nY5aHqCDsUMT12mVuYv0V702QwM0fGlLjnV190Wi2KxZtu7YJrqIm5JmI8wDBuldr9hjOu/lIhWdLv3BiqaaTiuvm/WbgwDEeQUBLPAqbSKOtGmAPi4F3iLZoWASM32yxmQ5CKYiWR2jEYOTkSSgJY1mS5sldpZ74aosrRwKGtNroodHrqRoj8d6gu+piM6haqrwOQZ/lmyL3UlHe0SSBA25benpqEP66u8PI0nPdzMqHAgoPM2WgKrICmxGz2NTx9aMd9dCtKdXBnPoRX4t/Zjp2rLoWIs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
